### ISSUE TITLE
  Database.insert(collection='posts',data=self.json())

### ISSUE THREAD

**Issue by rahulmasal** [schoolofcode-me/web_blog#1]
Traceback (most recent call last):
  File "d:\myprograms\python\test.py", line 9, in <module>
    post.save_to_mongo()
  File "d:\myprograms\python\post.py", line 15, in save_to_mongo
    Database.insert(collection='posts',data=self.json())
TypeError: insert() got an unexpected keyword argument 'data'

**Comment by jslvtr** [comment]
Hey @rahulmasal , this problem is likely to do with a small mistake in your code for the Database class. The best place to ask for questions is in the Course Q&A!
